---
kind: Template
apiVersion: v1
metadata:
  name: dovecot
  annotations:
    description: dovecot container for IMAP server
    tags: imap-server
labels:
  template: dovecot
  group: dovecot
  version: 3.1.3
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "dovecot-container"
  spec:
    dockerImageRepository: "phracek/dovecot"
  tags:
    - name: "latest"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "dovecot-container"
  spec:
    selector:
      name: "dovecot-container"
    strategy:
      type: "Rolling"
    triggers:
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "dovecot-container"
          from:
            kind: "ImageStreamTag"
            name: "dovecot:latest"
    replicas: 1
    template:
      metadata:
        name: "dovecot-container"
        labels:
          name: "dovecot-container"
      spec:
        containers:
          - name: "dovecot-container"
            image: "dovecot:latest"
            volumeMounts:
              - mountPath: /var/spool/postfix
                name: spool-postfix
              - mountPath: /var/spool/mail
                name: spool-mail
              - mountPath: /var/log
                name: log
        volumes:
        #  - name: var
        #    emptyDir:
        #      medium: Memory
          - name: spool-postfix
            emptyDir: {}
          - name: spool-mail
            emptyDir: {}
          - name: log
            emptyDir: {}
