---
kind: Template
apiVersion: v1
metadata:
  name: postfix
  annotations:
    description: postfix with dovecot as IMAP server
    tags: imap-server
labels:
  template: postfix
  group: postfix
  version: 3.1.3
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "postfix-dovecot-container"
  spec:
    dockerImageRepository: "phracek/postfix"
  tags:
    - name: "latest"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "postfix-dovecot-container"
  spec:
    selector:
      name: "postfix-dovecot-container"
    strategy:
      type: "Rolling"
    triggers:
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "postfix-dovecot-container"
          from:
            kind: "ImageStreamTag"
            name: "postfix:latest"
    replicas: 1
    template:
      metadata:
        name: "postfix-dovecot-container"
        labels:
          name: "postfix-dovecot-container"
      spec:
        containers:
          - name: "postfix-dovecot-container"
            image: "postfix:latest"
            ports:
              - containerPort: 10025
              - containerPort: 10587
              - containerPort: 10465
            volumeMounts:
              - mountPath: /var/spool/postfix
                name: spool-postfix
              - mountPath: /var/spool/mail
                name: spool-mail
              - mountPath: /var/log
                name: log
        volumes:
        #  - name: var
        #    emptyDir:
        #      medium: Memory
          - name: spool-postfix
            emptyDir: {}
          - name: spool-mail
            emptyDir: {}
          - name: log
            emptyDir: {}
